#!/bin/sh
#
# Based on z3bra script <git.z3bra.org>

if [ "$1" == "-h" ]; then
    printf "%s\n" "usage: colors [-hx]"
    exit 0
elif [ "$1" == "-x" ]; then
    for num in 0 1 2 3 4 5 6 7; do
        CN=$(xrdb -q | awk -F ':' -v c="^*color$num:" '$0 ~ c {print $2}')
        printf "\033[0;3%sm%s\033[0m " $num $CN
    done
    printf "\n"
     for num in 0 1 2 3 4 5 6 7; do
        printf "\033[0;3%sm%s\033[0m " $num '#######'
    done
    printf "\n"
    for num in 0 1 2 3 4 5 6 7; do
        printf "\033[1;3%sm%s\033[0m " $num '#######'
    done
    printf "\n"
    for num in 0 1 2 3 4 5 6 7; do
        CN=$(xrdb -q | awk -F ':' -v c="^*color$((num+8)):" '$0 ~ c {print $2}')
        printf "\033[1;3%sm%s\033[0m " $num $CN
    done
else
    for num in 0 1 2 3 4 5 6 7; do
        printf "\033[0;3%sm%s\033[0m " $num '#'
    done
    printf "\n"
    for num in 0 1 2 3 4 5 6 7; do
        printf "\033[1;3%sm%s\033[0m " $num '#'
    done
fi
printf "\n"
