#!/bin/sh
#
# Copyright (c) 2015, 2016 aured <aured+prj@openmailbox.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

DATE=$(date +%F\ %T)
DDNSUC_DIR=$HOME/.ddnsuc
DDNSUC_URL=$*
IP_FILE=$DDNSUC_DIR/ddnsuc.pub
RND=$(awk -v min=1 -v max=3 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')

[ ! "$(command -v curl)" ] && echo "'curl' is not installed." && exit 1
[ -z "$DDNSUC_URL" ] && echo "usage: ddnsuc file | url ..." && exit 1
[ -d "$DDNSUC_DIR" ] || mkdir -p $DDNSUC_DIR
[ -f "$DDNSUC_URL" ] && DDNSUC_URL=$(cat $DDNSUC_URL)
[ -f "$IP_FILE" ] && OLD_IP=$(cat $IP_FILE)

case $RND in
    1) NEW_IP=$(dig +short myip.opendns.com -4 -t A @resolver1.opendns.com) ;;
    2) NEW_IP=$(dig +short o-o.myaddr.l.google.com -4 -t TXT @ns1.google.com \
                | tr -d '"') ;;
    3) NEW_IP=$(dig +short whoami.akamai.net -4 -t A @ns1-1.akamaitech.net) ;;
    *) echo "[$DATE] (EE) RND=$RND" && exit 1 ;;
esac

if [ -z "$NEW_IP" ]; then
    echo "[$DATE] (EE) RND=$RND, NEW_IP=$NEW_IP"
    exit 1
elif [ "$NEW_IP" != "$OLD_IP" ]; then
    for url in $DDNSUC_URL; do
        echo "[$DATE] (II) $(curl -sS $url)"
    done
    echo -n "$NEW_IP" > $IP_FILE
fi

exit 0
