#!/bin/sh
#
# Copyright (c) 2016 aured <aured+prj@openmailbox.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

TODO_FILE="$HOME/.todo"
TMP_FILE="/tmp/todofile"
INTERVAL=10

item_append() {
    _mode='a'
    _nb_item='$'
    item_new
    item_write
}

item_delete() {
    _mode='d'
    item_view
    echo "${_nb_item}  ${_item}"
    echo -n "Remove item ${_nb_item}? [no] "
    read _answer
    case ${_answer} in
        y|yes)
            item_write
            ;;
    esac
}

item_edit() {
    _mode='c'
    item_view
    echo "Old item: ${_item}"
    item_new
    item_write
}

item_empty() {
    [ -z "${1}" ] && exit 1
}

item_insert() {
    _mode='i'
    item_number
    item_new
    item_write
}

item_new() {
    echo -n "New item: "
    read _new_item
    item_empty "${_new_item}"
}

item_number() {
    _nb_item=${OPTARG}
    case ${_nb_item} in
        ''|*[!0-9]*)
            exit 1
            ;;
    esac
}

item_purge() {
    echo -n "Purge todo file? [no] "
    read _answer
    case ${_answer} in
        y|yes)
            : > ${TODO_FILE}
            echo "Todo file purged!"
            ;;
    esac
}

item_view() {
    item_number
    _item=$(sed -n "${_nb_item}p" ${TODO_FILE})
    item_empty "${_item}"
}

item_write() {
    if [ -s "${TODO_FILE}" ]; then
        sed -e "${_nb_item} ${_mode} ${_new_item}" "${TODO_FILE}" > \
             "${TMP_FILE}"
        mv "${TMP_FILE}" "${TODO_FILE}"
    else
        echo "${_new_item}" > "${TODO_FILE}"
    fi
}

todo_list() {
    echo ""
    echo "                    TODO"
    echo "      <<---------------------------->>"
    echo ""
    nl -b a ${TODO_FILE}
    echo ""
}

todo_next_list() {
    echo " .
..: TODO
======================================================================="
    nl -n rz -b a ${TODO_FILE}
}

todo_no_list() {
    cat ${TODO_FILE}
}

todo_loop() {
    while true; do
        clear
        todo_list
        sleep ${INTERVAL}
    done
}

usage() {
    echo "\
usage: todo [-aclnPsx] [-d line_number] [-e line_number] [-f todo_file]
            [-i line_number]"
    exit 1
}

[ -f "${TODO_FILE}" ] || touch ${TODO_FILE}
[ $# -gt 0 ] || todo_list
while getopts "acd:e:f:i:lnPsx" _opt; do
    case ${_opt} in
        a) item_append ;;
        c) clear && todo_list ;;
        d) item_delete ;;
        e) item_edit ;;
        f) TODO_FILE="${OPTARG}" ;;
        i) item_insert ;;
        l) todo_loop ;;
        n) todo_no_list ;;
        P) item_purge ;;
        s) todo_list ;;
        x) todo_next_list ;;
        *) usage ;;
    esac
done

exit 0
